/*
 * Interface.java
 *
 * Created on 22 mei 2007, 11:48
 */

package nl.fab1an.java.world;
import java.util.*;

/**
 *
 * @author  Fabian
 */
public class Gui extends javax.swing.JFrame {
    
    private Game game;
    private Player player;
    
    public Gui(Game game, Player player) {
        this.game = game;
        this.player = player;
        initComponents();
        jConsole.setText(null);
        updateInterface();
    }
    
    /**
     * Updates the north/west/east/south buttons
     */
    public void updateInterface() {
        jNorth.setEnabled(false);
        jEast.setEnabled(false);
        jSouth.setEnabled(false);
        jWest.setEnabled(false);
        if (player.getCurrentArea().getExit("north") != null) jNorth.setEnabled(true);
        if (player.getCurrentArea().getExit("east") != null) jEast.setEnabled(true);
        if (player.getCurrentArea().getExit("south") != null) jSouth.setEnabled(true);
        if (player.getCurrentArea().getExit("west") != null) jWest.setEnabled(true);
    }
    
    public void disableInterface() {
        this.setEnabled(false);
    }
    
    public void setGame(Game game) { this.game = game; }
    public Game getGame() { return game; }
    
    public void clear() {
        jConsole.setText("");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jConsole = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jWest = new javax.swing.JButton();
        jNorth = new javax.swing.JButton();
        jEast = new javax.swing.JButton();
        jSouth = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInput.setText("Enter command here");
        jInput.setToolTipText("<html>\n<b>Sample commands</b>:<br>\n<br>\n<b>go</b> east <br>\n<b>look</b> <br>\n<b>take</b> item <br>\n<b>drop</b> item <br>\n<b>use</b> item <br>\n<b>give</b> player item <br>\n<b>inventory</b> <br>\n<b>help</b><br>");
        jInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputActionPerformed(evt);
            }
        });
        jInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInputFocusLost(evt);
            }
        });

        jConsole.setColumns(20);
        jConsole.setEditable(false);
        jConsole.setLineWrap(true);
        jConsole.setRows(5);
        jConsole.setText("Console");
        jScrollPane1.setViewportView(jConsole);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jWest.setText("west");
        jWest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWestActionPerformed(evt);
            }
        });

        jNorth.setText("north");
        jNorth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNorthActionPerformed(evt);
            }
        });

        jEast.setText("east");
        jEast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEastActionPerformed(evt);
            }
        });

        jSouth.setText("south");
        jSouth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSouthActionPerformed(evt);
            }
        });

        jLabel1.setText("Go into direction:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jWest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEast))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jSouth))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jNorth))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNorth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWest)
                    .addComponent(jEast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSouth)
                .addContainerGap())
        );

        jLabel2.setText("Logo komt hier :)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jInput)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
private void jInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputActionPerformed
    try {
        player.getParser().command(jInput.getText());
    } catch (Exception e) {
        println("Eeheuhah?!");
    }
    jInput.setText("");
}//GEN-LAST:event_jInputActionPerformed

private void jSouthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSouthActionPerformed
    player.getParser().command("go south");
}//GEN-LAST:event_jSouthActionPerformed

private void jNorthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNorthActionPerformed
    player.getParser().command("go north");
}//GEN-LAST:event_jNorthActionPerformed

private void jWestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWestActionPerformed
    player.getParser().command("go west");
}//GEN-LAST:event_jWestActionPerformed

private void jEastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEastActionPerformed
    player.getParser().command("go east");
}//GEN-LAST:event_jEastActionPerformed

private void jInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputFocusLost
    if (jInput.getText().equals("")) jInput.setText("Enter command here");
}//GEN-LAST:event_jInputFocusLost

private void jInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputFocusGained
    if (jInput.getText().equals("Enter command here")) jInput.setText(null);
}//GEN-LAST:event_jInputFocusGained


public void println(String message) {
    jConsole.append(message + "\n");
    jConsole.setCaretPosition(jConsole.getText().length());
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jConsole;
    private javax.swing.JButton jEast;
    private javax.swing.JTextField jInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jNorth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSouth;
    private javax.swing.JButton jWest;
    // End of variables declaration//GEN-END:variables
    
}
